Minor change for standardisation of variables
openMF/ph-ee-operations-app pull request #24
Opened 2022-06-24 11:34 UTC by ankita10r

Minor change for standardisation of variables in application.yml

@avikganguly01: Please review

Other related PR:
https://github.com/openMF/ph-ee-connector-channel/pull/36

2022-06-25 14:37 UTC, avikganguly01 requested changes
Driver class name not following naming conventions.

2022-06-29 07:59 UTC, ankita10r commented
@avikganguly01 fixed it

2022-06-29 10:48 UTC, avikganguly01 requested changes

2022-06-29 10:48 UTC, avikganguly01 commented on src/main/resources/application.yml
> +      driverclass-name: com.mysql.cj.jdbc.Driver
Where is the corresponding source code change?

2023-06-02 06:59 UTC, closed without merging