Added migration script for error_info column in txn_request table
openMF/ph-ee-operations-app pull request #45
Opened 2023-01-18 09:22 UTC by danishjamal104

## Description

* Added migration script for adding `ERROR_INFORMATION` field in transaction_request table.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above. 

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-01-18 09:23 UTC, danishjamal104 commented
@fynmanoj I have tested this migratino script in SIT , and its working so we can merge this PR. Thanks :)

2023-01-18 12:10 UTC, fynmanoj requested changes

2023-01-18 12:10 UTC, fynmanoj commented on src/main/java/org/apache/fineract/operations/TransactionRequest.java
> +    @Column(name = "error_information")
let's follow the same variable naming convention as already available in the same class. ie, upper case column name

2023-02-07 11:29 UTC, fynmanoj approved these changes

2023-02-07 11:29 UTC, merged